/**
 * Generated by `supabase gen types typescript`.
 * Regenerate after migrations:
 *   pnpm dlx supabase gen types typescript --project-id <PROJECT_ID> > lib/supabase/types.ts
 *
 * Stub kept here so the project compiles before the first migration runs.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
